back to ohi-science from jules32
App launched fatally to https://jules32.shinyapps.io/esp_app/

To https://08b794726d88febb92a61b388d03348b9dbcc776@github.com/OHI-Science/esp.git
 ! [rejected]        HEAD -> app (non-fast-forward)
error: failed to push some refs to 'https://08b794726d88febb92a61b388d03348b9dbcc776@github.com/OHI-Science/esp.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
From https://github.com/OHI-Science/esp
   7c93cd9..92f51ae  gh-pages   -> origin/gh-pages
fatal: branch 'app' does not exist